### ISSUE TITLE
README.md example does not seem to work

### ISSUE THREAD

**Issue by JeremyGamer13** [meower-media-co/CLJS#1]
The README.md example seems to show using `await` on functions like `.send()` or `.connect()`, but these don't actually seem to wait for their completion or even return a `Promise` at all.

You can easily see this if you try to `await client.connect()` and then `await client.send()` with any send options, since it'll just error saying that there is no open connection.

**Comment by williamhorning** [comment]
@JeremyGamer13 i have no clue why the example differs so much from the actual implementation, but i'll make a PR to fix this eventually

**Comment by williamhorning** [comment]
@JeremyGamer13 this should be fixed in the latest release. see the docs: https://jsr.io/@jersey/cloudlink/doc
