### ISSUE TITLE
4.1.2 has breaking changes

### ISSUE THREAD

**Issue by mybearworld** [meower-media-co/CLJS#2]
4.1.2 has breaking changes, which really shouldn't be in a patch version update - so e.g. `pnpm update` will break anything using this on 4.1.2

**Suggestion:** Publish 4.1.3 which reverts back to 4.1.1's state so that `pnpm update` and friends are fixed, then publish 5.0.0 with the breaking changes

**Comment by williamhorning** [comment]
ah shoot, i've been used to not making major releases of stuff for breaking changes because of bolt/lightning. ill yank 4.1.2 from wherever i can and get 4.1.3 and 5.0.0 out later this weekend

**Comment by mybearworld** [comment]
Great, thanks!

**Comment by williamhorning** [comment]
okay, so, on npm, 4.1.2 is unpublished, 4.1.1 and 5.0.0 are the two latest versions
on jsr, 4.1.2 is yanked, and 5.0.0 is the latest version
on .land, 4.1.2 is still there, but the latest two versions are 4.1.3 and 5.0.0

i'm so sorry for all the chaos and confusion caused by this!
